# Generated by Django 2.1.5 on 2019-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorUsername', models.CharField(max_length=200)),
                ('patientUsername', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=100)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='yearsOfExperience',
            field=models.IntegerField(default=0),
        ),
    ]
