# Generated by Django 2.1.5 on 2019-01-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20190119_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorUsername',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientUsername',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Patient'),
        ),
    ]
