# Generated by Django 2.1.5 on 2019-01-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='dp.png', upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='dp.png', upload_to='patient/'),
        ),
    ]
